### ISSUE TITLE
Undefined method < for nihlclass

### ISSUE THREAD

**Issue by nynhex** [gorails-screencasts/chatrooms#2]
Was doing a diff between what I was writing and the cloned repo I was playing around with.  

3 things happen:

1.) When a message is entered it shows broadcasted but does not display in the show page/chatroom page.

2.) Sidebar does not show joined channel(s)

3.) When you manually refresh the page to see the message that was not displayed/pushed to the browser you get the Undefined method < for Nihlclass

![screenshot 2016-09-06 06 05 51](https://cloud.githubusercontent.com/assets/13086902/18271552/45963f18-73f8-11e6-9533-8ac415f5d166.png)

I can fix this and do a PR if you like.

**Comment by excid3** [comment]
Not sure about the first 2. 

As for #3, it probably makes sense to set the last_read_at to the time when you join a channel and create the `chatroom_user` record. This way you don't see all the old posts as "unread" because there might be a ton of them and that'd be ridiculous.

Open some PRs and show me what you're thinkin?

**Comment by nynhex** [comment]
#1/#2 were bugs that were introduced when the coffee/js was changed from the 4th episode moving forward.  Whether using my repo (slightly altered from your tutorial) or direct cloning yours and running it, the messages sporadically show up, and the chatroom sidebar never populates.  Rails 5.0.0.0 (and 5.0.0.1), Ruby 2.3.1

Agreed on #3, I have a few ideas on this.  I'll fork and see what I can come up.  Will PR when I get something working 👍

**Comment by nynhex** [comment]
Ok so 2. was totally my oversight.  When I join a channel it will populate the sidebar with the channel name(s) joined.  However when creating a channel it brings you into the channel without actually doing the join.  This creates a weird behavior especially on the UX side.  I create the channel and auto-join it which makes sense, but the join doesn't actually take place.

So there's two reasonable solutions to this.

1.) Simple redirect to `chatrooms_path` on successful creation of chatroom
or better yet
2.) On chatroom save, join the `current_user` to the channel and of course redirect.

I'm going to work on option two.  I think it makes more sense to create -> join -> enter chat.

**Comment by nynhex** [comment]
All PRs have been issued.  Please send back if they need to be further fleshed out or iterated over.
